import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Expose } from 'class-transformer';

export class PortfolioResponseDto {
  @ApiProperty({
    description: 'Unique identity tracking index UUID',
    example: 'a62888cf-90b1-4f71-a080-60b6426dd531',
  })
  @Expose()
  id: string;

  @ApiProperty({
    description: 'The candidate profile identifier link reference',
    example: 'ebd6a6cc-c760-466d-8bfe-bb36d7aeb9e3',
  })
  @Expose()
  candidateId: string;

  @ApiProperty({
    description: 'The title of the portfolio item card',
    example: 'Clinically - clinic & healthcare website',
  })
  @Expose()
  title: string;

  @ApiPropertyOptional({
    description: 'Text summaries logging details',
    example: 'Built using Next.js...',
  })
  @Expose()
  description: string | null;

  @ApiProperty({
    description:
      'The absolute public storage URL generated by the system upload',
    example:
      'https://storage.googleapis.com/your-bucket/portfolios/preview.png',
  })
  @Expose()
  thumbnailUrl: string;

  @ApiPropertyOptional({
    description: 'Outbound target production URL link',
    example: 'https://clinically-demo.dev',
  })
  @Expose()
  projectUrl: string | null;

  @ApiProperty({
    description: 'Record initialization timestamp',
    example: '2026-03-01T10:00:00.000Z',
  })
  @Expose()
  createdAt: Date;

  @ApiProperty({
    description: 'Record modification tracking value log',
    example: '2026-03-01T12:30:00.000Z',
  })
  @Expose()
  updatedAt: Date;
}
