export enum JobCategory {
  DESIGN = 'DESIGN',
  SALES = 'SALES',
  MARKETING = 'MARKETING',
  BUSINESS = 'BUSINESS',
  HUMAN_RESOURCE = 'HUMAN_RESOURCE',
  FINANCE = 'FINANCE',
  ENGINEERING = 'ENGINEERING',
  TECHNOLOGY = 'TECHNOLOGY',
}
