export enum UserRole {
  CANDIDATE = 'CANDIDATE',
  COMPANY_OWNER = 'COMPANY_OWNER',
  HR_MANAGER = 'HR_MANAGER',
  RECRUITER = 'RECRUITER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  MODERATOR = 'MODERATOR',
}
